### ISSUE TITLE
Problem with puppet v4

### ISSUE THREAD

**Issue by Tomelin** [razorsedge/puppet-snmp#103]
Hi,

This is module with problem puppet v4.

is it:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Unknown variable: '::snmp_agentaddress'. at /etc/puppetlabs/code/environments/production/modules/snmp/manifests/params.pp:19:19 on node mail.tolidistribuidora.com.br","issue_kind":"RUNTIME_ERROR","stacktrace":["Warning: The 'stacktrace' property is deprecated and will be removed in a future version of Puppet. For security reasons, stacktraces are not returned with Puppet HTTP Error responses."]}
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by blackknight36** [comment]
Do you have strict variables enabled?  manifests/params.pp appears to reference $::snmp_agentaddress however puppet should fall back to the default value when that variable is undefined.

**Comment by razorsedge** [comment]
@Tomelin Version 3.x of this module does not support Puppet 4's STRICT_VARIABLES=true.  I have several PRs in the works for fixing this.

**Comment by razorsedge** [comment]
Closed by #102
