### ISSUE TITLE
Using an array for ro_community breaks snmptrapd

### ISSUE THREAD

**Issue by djschaap** [razorsedge/puppet-snmp#106]
manifests/init.pp says ro_community can be either strings or arrays of strings.  When an array is provided, snmpd.conf is generated properly, but snmptrapd.conf does not loop over each community as expected, resulting in an invalid config file. [correction: ro_community6 is not relevant for snmptrapd.conf]

**Comment by razorsedge** [comment]
Fixed in version [3.8.1](https://forge.puppet.com/razorsedge/snmp/3.8.1/readme).
