### ISSUE TITLE
Debian Stretch (new stable) use a different user for snmpd

### ISSUE THREAD

**Issue by eLvErDe** [razorsedge/puppet-snmp#108]
Hi,

Here is the new user for snmpd:

```
Debian-snmp     Debian-snmp     /usr/sbin/snmpd -Lsd -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux mteTrigger mteTriggerConf -f
```
```
cat /etc/debian_version 
9.0
```
Regards, Adam.

**Comment by hotid** [comment]
```
diff --git a/manifests/params.pp b/manifests/params.pp
index 1c9566d..c531828 100644
--- a/manifests/params.pp
+++ b/manifests/params.pp
@@ -472,8 +472,14 @@ class snmp::params {
       $sysconfig                = '/etc/default/snmpd'
       $var_net_snmp             = '/var/lib/snmp'
       $varnetsnmp_perms         = '0755'
-      $varnetsnmp_owner         = 'snmp'
-      $varnetsnmp_group         = 'snmp'
+
+      if (versioncmp($::operatingsystemmajrelease, '9') >= 0) {
+        $varnetsnmp_owner = 'Debian-snmp'
+        $varnetsnmp_group = 'Debian-snmp'
+      } else {
+        $varnetsnmp_owner         = 'snmp'
+        $varnetsnmp_group         = 'snmp'
+      }

       $client_package_name      = 'snmp'
       $client_config            = '/etc/snmp/snmp.conf'

```

**Comment by tamepenguin** [comment]
<pre>
diff --git a/tmp/origsnmp/manifests/params.pp b/manifests/params.pp
index 1c9566d..15ee810 100644
--- a/tmp/origsnmp/manifests/params.pp
+++ b/manifests/params.pp
@@ -463,17 +463,22 @@ class snmp::params {
       $trap_service_name        = 'snmptrapd'
     }
     'Debian': {
+      if $::operatingsystemmajrelease == "9" {
+        $varnetsnmp_owner = "Debian-snmp"
+        $varnetsnmp_group = "Debian-snmp"
+      } else {
+        $varnetsnmp_owner = "snmp"
+        $varnetsnmp_group = "snmp"
+      }
       $package_name             = 'snmpd'
       $service_config           = '/etc/snmp/snmpd.conf'
       $service_config_perms     = '0600'
       $service_config_dir_group = 'root'
       $service_name             = 'snmpd'
-      $snmpd_options            = '-Lsd -Lf /dev/null -u snmp -g snmp -I -smux -p /var/run/snmpd.pid'
+      $snmpd_options            = "-Lsd -Lf /dev/null -u $varnetsnmp_owner -g $varnetsnmp_group -I -smux -p /var/run/snmpd.pid"
       $sysconfig                = '/etc/default/snmpd'
       $var_net_snmp             = '/var/lib/snmp'
       $varnetsnmp_perms         = '0755'
-      $varnetsnmp_owner         = 'snmp'
-      $varnetsnmp_group         = 'snmp'
 
       $client_package_name      = 'snmp'
       $client_config            = '/etc/snmp/snmp.conf'
</pre>
Altough systemd does not use /etc/default/snmpd in this case, it's confusing to have settings different in different places.
Also, there is apparently a Debian remix without systemd :)

**Comment by hostingnuggets** [comment]
Any news regarding this issue?

**Comment by razorsedge** [comment]
PR in #109

**Comment by pawel-kuwalek** [comment]
update, PR in #113

**Comment by xraystyle** [comment]
@razorsedge Are you still maintaining this project? We're still hoping to get https://github.com/razorsedge/puppet-snmp/pull/113 merged in so we can use it without forking this module.

**Comment by razorsedge** [comment]
Merged into the `develop` branch.

**Comment by razorsedge** [comment]
Released with [razorsedge/snmp](https://forge.puppet.com/razorsedge/snmp) version 3.9.0.
