### ISSUE TITLE
configuring extend parameters

### ISSUE THREAD

**Issue by tjungbauer** [razorsedge/puppet-snmp#115]
Hi, 

This is more a feaure request than a bug.

I recently started to deploy snmpd config using puppet. Unfortunately I saw that some hosts are failing, because custom cripts are used to check specific items. 

Is there a possibility to add "extend" configuration parameters, or is there a reason why they have not been added?

For instance:
extend  pcluster_check_space  /bin/sh /usr/local/scripts/check_pcluster.sh space

Expectation would be for instance:
extend   => ['pcluster_check_space  /bin/sh /usr/local/scripts/check_pcluster.sh space',
                  ],

br
Thomas

**Comment by razorsedge** [comment]
The only reason why `extend` has not been added is that no one had requested the feature and that `snmpd_config` is able to address any non-native parameters.  I will look at PR #118 .

**Comment by razorsedge** [comment]
Released with [razorsedge/snmp](https://forge.puppet.com/razorsedge/snmp) version 3.9.0.
