### ISSUE TITLE
creating snmpv3 users fails with passphrases containing spaces

### ISSUE THREAD

**Issue by Seegras** [razorsedge/puppet-snmp#33]
Fix is simple, in manifests/snmpv3_user.pp 

  if $privpass {
    $cmd = "createUser ${title} ${authtype} \\\"${authpass}\\\" ${privtype} \\\"${privpass}\\\""
  } else {
    $cmd = "createUser ${title} ${authtype} \\\"${authpass}\\\""
  }

**Comment by razorsedge** [comment]
Merged.

**Comment by razorsedge** [comment]
Shipped [v3.5.0](https://forge.puppetlabs.com/razorsedge/snmp/3.5.0/) to the Forge.
