### ISSUE TITLE
CentOS 7.1 breaks params.rb

### ISSUE THREAD

**Issue by seitzbg** [razorsedge/puppet-snmp#44]
$majdistrelease = regsubst($::operatingsystemrelease,'^(\d+)\.(\d+)','\1')

Does not work on CentOS 7.1.1503. That variable does not seem to exist.

lsbdistdescription => CentOS Linux release 7.1.1503 (Core)
lsbdistrelease => 7.1.1503
lsbmajdistrelease => 7
lsbminordistrelease => 1

Thus you get:

Mar 31 17:43:10 b0c008ash2001 puppet-user[42116]: comparison of String with 5 failed at /var/lib/puppet/repo/modules/snmp/manifests/params.pp:246 on node b0c008ash2001.mgmt.symcpe.net

TIA,

**Comment by razorsedge** [comment]
What value does `facter operatingsystemmajrelease` return?

**Comment by razorsedge** [comment]
Which version of the centos-release package do you have installed?  You should have release `el7.centos.2.8`, otherwise it is a CentOS bug. http://lists.centos.org/pipermail/centos-announce/2015-April/021010.html

**Comment by seitzbg** [comment]
Yep you can close this, CentOS 7.1 screwed up and fixed in latest :)
Thanks dude!
