### ISSUE TITLE
Not possible to not start snmptrapd service

### ISSUE THREAD

**Issue by tlimoncelli** [razorsedge/puppet-snmp#52]
On RedHat systems, there doesn't seem to be a way to start snmpd without also starting snmptrapd.  The module enables both or neither.  If I set:

```
    trap_service_ensure => 'stopped',
    trap_service_enable => false,
```

snmptrapd still gets started.

Is the intentional?  Is it bad to run snmpd without snmptrapd?  We don't do anything with traps in our environment.

**Comment by razorsedge** [comment]
Tom,

By default `trap_service_ensure` is set to `stopped` and `trap_service_enable` to `false` in params.pp.  Using just `include ::snmp`, you should only have the snmpd running.  Normal operation does not require snmptrapd.

**Comment by tlimoncelli** [comment]
Thanks for the info.  I now see that I was misreading the code.  Yes, it all works as expected.

Thanks!
