### ISSUE TITLE
Multiple rocommunity,rwcommunity

### ISSUE THREAD

**Issue by linuxdan** [razorsedge/puppet-snmp#57]
Your module can only put one rocommunity and one rwcommunity line in snmpd.conf

I need to put more than one of each.

I may be able to contribute a solution

**Comment by TomOnTime** [comment]
This is fixed in https://github.com/razorsedge/puppet-snmp/pull/55.  Any chance we can get that merged?

**Comment by razorsedge** [comment]
Merged.

**Comment by razorsedge** [comment]
Shipped [v3.5.0](https://forge.puppetlabs.com/razorsedge/snmp/3.5.0/) to the Forge.
