### ISSUE TITLE
snmpwalk fails after installing this module

### ISSUE THREAD

**Issue by srianirudh84** [razorsedge/puppet-snmp#58]
Hi ,

I install this module with the following config:

snmp::snmpv3_user { 'user':
  authtype => 'MD5',
  authpass => 'authpass',
  privtype => 'DES',
  privpass => 'privpass',
}
class { 'snmp':
  agentaddress => [ 'udp:161'],
  ro_network => '0.0.0.0' ,
  contact => 'it-team@domain',
  location => 'US',
  snmpd_config => [ 'rouser user' ],
}

This installes the snmp package successfully and then when i run snmpwalk from a different host, it fails.

Any idea ??

**Comment by srianirudh84** [comment]
snmpwalk -v3 -l authPriv -a md5 -A authpass -x des -X privpass -u user <HOSTNAME> gives me the following error :
No log handling enabled - turning on stderr logging
snmpwalk: Authentication failure (incorrect password, community or key)

**Comment by srianirudh84** [comment]
@razorsedge 

Am i missing something here in the snmp class ? Is this is correct order of invoking the classes ?

**Comment by razorsedge** [comment]
@srianirudh84 Try changing the parameter `snmpd_config => [ 'rouser user' ],` to `snmpd_config => [ 'rouser user authPriv' ],`.

**Comment by brahama** [comment]
Hi @razorsedge , I have the samme problem. Just using the example as in the Readme and if i create the user manually it works ok.

::snmp::snmpv3_user { 'user':
    authpass => '123456789',
    privpass => '123456789',
  }

  class { '::snmp':
    snmpd_config => [ 'rouser user authPriv' ],
  }

Thanks!

**Comment by razorsedge** [comment]
closing
