### ISSUE TITLE
smuxsocket disabling

### ISSUE THREAD

**Issue by ggeldenhuis** [razorsedge/puppet-snmp#60]
Hi
On CentOS 7.1.1503 snmpd listens on tcp port 199 by default. I tried to switch it off via startup flags but unfortunately these get ignored. Specifically "-I -smux" From the little reading I have done this does not seem to be widely used and is turned off on Ubuntu 14. The only way to disable it is by giving it the wrong configuration:
smuxsocket 1.0.0.0

Now at the moment this is not surfaced as a parameter in the module. Before I add it as an option in a PR, I just wanted to get an opinion on whether it is worth adding. I did not see an option for adding arbitrary config, but it might be due to lack of coffee early in the morning.

Regards

**Comment by razorsedge** [comment]
There is a snmpd safety valve parameter to add in anything the module does not natively support.

**Comment by razorsedge** [comment]
closing
