### ISSUE TITLE
CI failing, Module sync out of date.

### ISSUE THREAD

**Issue by mterzo** [razorsedge/puppet-snmp#75]
I updated to your latest development and tried to just build with travis:
https://travis-ci.org/mterzo/puppet-snmp/builds/158126929

Your module sync doesn't put any restrictions on the Json gem, which it's trying to pull down a version that does not work with ruby <= 2.0

Once you get past that you are getting puppet-lint 2.0.2 which the parameter for long lines changed from `--no-80chars-check` to `--no-140chars-check`

**Comment by jnquintin** [comment]
Corrected in the pr#79

**Comment by razorsedge** [comment]
This had been fixed in a37c2ae81a82380be5d7e7836098635c662f1617 and related commits to the `develop` branch..
