### ISSUE TITLE
No such file or directory errors

### ISSUE THREAD

**Issue by blackknight36** [razorsedge/puppet-snmp#83]
There appears to be an error when this module is first run that causes errors to show up in our puppet reports.  For example, the following errors occur during the first puppet run on a new host.

> Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock at /etc/puppetlabs/code/environments/ovirt_test/forge_modules/snmp/manifests/client.pp:85
> Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock at /etc/puppetlabs/code/environments/ovirt_test/forge_modules/snmp/manifests/client.pp:85
> Wrapped exception:
> No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock
> Error: /Stage[main]/Snmp::Client/File[snmp.conf]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock at /etc/puppetlabs/code/environments/ovirt_test/forge_modules/snmp/manifests/client.pp:85
> Info: Class[Snmp::Client]: Unscheduling all events on Class[Snmp::Client]Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock at /etc/puppetlabs/code/environments/ovirt_test/forge_modules/snmp/manifests/client.pp:85
> Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock at /etc/puppetlabs/code/environments/ovirt_test/forge_modules/snmp/manifests/client.pp:85
> Wrapped exception:
> No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock
> Error: /Stage[main]/Snmp::Client/File[snmp.conf]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/snmp/snmp.conf20161121-20105-1teyemp.lock at /etc/puppetlabs/code/environments/ovirt_test/forge_modules/snmp/manifests/client.pp:85
> Info: Class[Snmp::Client]: Unscheduling all events on Class[Snmp::Client]

**Comment by razorsedge** [comment]
@blackknight36 What versions of Puppet, Puppet server, and OS are we dealing with?  Which version of the razorsedge/snmp module?

**Comment by blackknight36** [comment]
@razorsedge We're running puppetserver 2.7.2 with puppet-agent 1.9.10 on CentOS 7.2.  I've also seen this error on Fedora based systems.  I believe the issue is that the snmp::client class attempts to create a config file before the /etc/snmp directory exists.  This directory is provided by the net-snmp package so it may be possible to fix this by adding a package requirement on the file resource.

**Comment by razorsedge** [comment]
@blackknight36 Odd.  I'm looking at the [latest code](https://github.com/razorsedge/puppet-snmp/blob/master/manifests/client.pp#L92) and the `File['snmp.conf']` is using a `require` as long as you are [not on Suse](https://github.com/razorsedge/puppet-snmp/blob/master/manifests/client.pp#L75). Either the `$req` is not getting set, or maybe Puppet 4  has issues with package aliases.

**Comment by blackknight36** [comment]
I'll have to set up a VM and run some more tests.  The error only occurs on the first puppet run, once the /etc/snmp directory is created the error goes away.

**Comment by blackknight36** [comment]
I believe I see the issue.  $req is set to require the snmp-client package which does not create the /etc/snmp directory.  /etc/snmp is provided by the net-snmp package on redhat based systems as shown by the rpm command.

username@dev27:/etc/snmp$ rpm -qf .
net-snmp-5.7.3-13.fc25.x86_64

$req should most likely be changed to $snmp::params::package_name since that is the correct package which manages the directory.

**Comment by blackknight36** [comment]
I've submitted PR #98 which should fix this on Redhat and Fedora based systems.

**Comment by elisiano** [comment]
I'm seeing this too. Since the PR has been merged, is there an ETA for when this can hit the forge?

**Comment by razorsedge** [comment]
I hope to get this pushed to the Forge by this weekend.

**Comment by razorsedge** [comment]
Closed by #98

**Comment by razorsedge** [comment]
3.8.0 has been pushed to the Forge.
